### ISSUE TITLE
Trouble with testing template function

### ISSUE THREAD

**Issue by gelio5** [gelio5/PS2020#3]
При попытке тестирования шаблонной функции появились ошибки линкера.
Вот так выглядит сообщение полученное при попытке компиляции:
====================[ Build | simple_test | Debug ]=============================
"D:\Program Files\JetBrains\CLion 2019.2.1\bin\cmake\win\bin\cmake.exe" --build D:\PS2020\Easy_1_2\cmake-build-debug --target simple_test
[ 25%] Built target Sorting
[ 50%] Built target gtest
[ 75%] Built target gtest_main
[ 87%] Linking CXX executable simple_test.exe
LINK Pass 1: command "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\simple_test.dir\objects1.rsp /out:simple_test.exe /implib:simple_test.lib /pdb:D:\PS2020\Easy_1_2\cmake-build-debug\src\tests\simple_test.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console ..\Sorting.lib ..\..\lib\gtest_maind.lib ..\..\lib\gtestd.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\simple_test.dir/intermediate.manifest CMakeFiles\simple_test.dir/manifest.res" failed (exit code 1120) with the following output:
test.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "bool __cdecl less<double>(double,double)" (??$less@N@@YA_NNN@Z) в функции "private: virtual void __cdecl Easy_1_1_lessTest_Test::TestBody(void)" (?TestBody@Easy_1_1_lessTest_Test@@EEAAXXZ)
simple_test.exe : fatal error LNK1120: неразрешенных внешних элементов: 1
NMAKE : fatal error U1077: "D:\Program Files\JetBrains\CLion 2019.2.1\bin\cmake\win\bin\cmake.exe" : возвращенный код "0xffffffff"
Stop.
NMAKE : fatal error U1077: "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\nmake.exe" : возвращенный код "0x2"
Stop.
NMAKE : fatal error U1077: "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\nmake.exe" : возвращенный код "0x2"
Stop.
NMAKE : fatal error U1077: "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\nmake.exe" : возвращенный код "0x2"
Stop.

**Comment by VargArt** [comment]
шаблоны не могут быть реализованы в cpp файле я об этом вам говорил

**Comment by gelio5** [comment]
Точно, забыл, исправлю. Спасибо
